name: al-grano-bot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - certifi # Add certifi here as a primary Conda dependency
  - pip:
      - python-telegram-bot
      - python-dotenv
      - openai
      - aiosqlite
      - youtube-transcript-api
      - python-readability
      - python-docx
      - PyPDF2
      - pytz
      - APScheduler
